# Generated by Django 3.1.2 on 2021-01-24 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['created_at'], 'verbose_name': 'Информация о заказе', 'verbose_name_plural': 'Информация о заказах'},
        ),
        migrations.AlterModelOptions(
            name='orderposition',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.TextField(choices=[('Нов', 'Новый заказ'), ('Вып', 'Выполняется'), ('Гот', 'Заказ готов')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.user'),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='api.order'),
        ),
    ]
