# Generated by Django 3.1.2 on 2021-01-26 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210126_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='full_price',
        ),
    ]
