GET http://localhost:8000/api/v1/orders/?full_price_min=200000
Content-Type: application/json

###
GET http://localhost:8000/api/v1/orders/
Content-Type: application/json

###
GET http://localhost:8000/api/v1/products/
Content-Type: application/json
#Authorization: Token f9b453a9cba690955cf93a244168c09a3a3e4760

###
POST http://localhost:8000/api/v1/products/
Content-Type: application/json
Authorization: Token f9b453a9cba690955cf93a244168c09a3a3e4760

{
    "name": "Iphone 5s",
    "description": "Если всё совсем плохо",
    "price": 30000.00
}

###
GET http://localhost:8000/api/v1/product-reviews/
Content-Type: application/json
Authorization: Token 23c447c408305cf0f99cf3a21a8fb9e11890ee8d

###

###
PUT  http://localhost:8000/api/v1/product-reviews/?id=2/
Content-Type: application/json
Authorization: Token 23c447c408305cf0f99cf3a21a8fb9e11890ee8d

  {
    "author": 2,
    "product": 1,
    "review": "Отлично",
    "score": 5
  }

###
GET http://localhost:8000/api/v1/product-collections/
Content-Type: application/json
Authorization: Token 23c447c408305cf0f99cf3a21a8fb9e11890ee8d

###
POST http://localhost:8000/api/v1/orders/
Content-Type: application/json
Authorization: Token 23c447c408305cf0f99cf3a21a8fb9e11890ee8d

{
    "user": 2,
    "positions": [
      {
        "product": 1,
        "quantity": 3
      }
    ],
    "status": "Нов"
}

###
PUT  http://localhost:8000/api/v1/product-reviews/
Content-Type: application/json
Authorization: Token 23c447c408305cf0f99cf3a21a8fb9e11890ee8d

{
  "score": 5
}

###
PATCH  http://localhost:8000/api/v1/orders/46/
Content-Type: application/json
Authorization: Token 23c447c408305cf0f99cf3a21a8fb9e11890ee8d

{
  "status": "Гот"
}
